name: Gardener - AWS

on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'kyma-project/kyma'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
      shoot:
        description: 'Shoot cluster name'
        required: true
        default: 'ci'
      skip:
        description: 'Skip modules'
        required: false
        default: 'monitoring,tracing,kiali,logging,console,cluster-users,dex'
      keep:
        description: 'Keep cluster alive'
        required: true
        default: true
  schedule:
    - cron: '0 * * * *' # every hour
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Create cluster, install helm
      timeout-minutes: 10
      env:
        GARDEN_KUBECONFIG: ${{ secrets.GARDEN_KUBECONFIG_AWS }}
        SHOOT_NAME: ${{ github.event.inputs.shoot }}
      run: |
        ./create-cluster-gardener-aws.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    - name: Download Kyma
      timeout-minutes: 2
      run: |
        ./download-kyma-charts.sh pbochynski/kyma kyma-js
    - name: Install Kyma
      timeout-minutes: 10
      run: |
        cd tests/fast-integration
        npm install
        ./kyma.js install -v
    - name: Run test
      timeout-minutes: 10
      run: |
        cd tests/fast-integration
        npx mocha test/2-commerce-mock.js
        npx mocha test/3-getting-started-guides.js
    - name: Uninstall Kyma
      if: ${{ always() }}
      run: |
        KEEP=${{ github.event.inputs.keep }}
        if [[ $KEEP == "true" ]]; then
          echo "Keeping cluster alive"
          exit 0
        fi
        echo "Deleting cluster ..."
        cd tests/fast-integration
        ./kyma.js uninstall -v
        export SHOOT_NAME=$(kubectl get cm shoot-info -n kube-system -ojsonpath='{.data.shootName}')
        kubectl --kubeconfig ./garden-kubeconfig.yaml annotate shoot $SHOOT_NAME confirmation.gardener.cloud/deletion=true
        kubectl --kubeconfig ./garden-kubeconfig.yaml delete shoot $SHOOT_NAME --force=true --wait=false

