name: Gardener - Azure

on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'kyma-project/kyma'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
      shoot:
        description: 'Shoot cluster name'
        required: true
        default: 'ci'
      skip:
        description: 'Skip modules'
        required: false
        default: 'monitoring,tracing,kiali,logging,console,cluster-users,dex'
      keep:
        description: 'Keep cluster alive'
        required: true
        default: 'false'
  schedule:
    - cron: '0 * * * *' # every hour
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v2
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Create cluster, install helm
      timeout-minutes: 15
      env:
        GARDEN_KUBECONFIG: ${{ secrets.GARDEN_KUBECONFIG }}
        SHOOT_NAME: ${{ github.event.inputs.shoot }}
      run: |
        ./create-cluster-gardener-azure.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    - name: Install Istio
      timeout-minutes: 5
      run: |
        ./install-istio.sh -f config-istio.yaml
    - name: Install Kyma
      timeout-minutes: 20
      run: |
        SKIP=${{ github.event.inputs.skip }}
        export SKIP_MODULES=${SKIP:-$SKIP_MODULES}
        ./download-kyma-charts.sh ${{ github.event.inputs.repository }} ${{ github.event.inputs.branch }}
        ./install-kyma-gardener.sh
    - name: Run End To End Test
      timeout-minutes: 10
      run: |
        cd fast-integration
        npm install
        npx mocha -b --inline-diffs --check-leaks
    - name: Uninstall Kyma
      if: ${{ always() }}
      run: |
        KEEP=${{ github.event.inputs.keep }}
        if [[ $KEEP == "true" ]]; then
          echo "Keeping cluster alive"
          exit 0
        fi
        echo "Deleting cluster ..."
        ./uninstall-kyma.sh
        export SHOOT_NAME=$(kubectl get cm shoot-info -n kube-system -ojsonpath='{.data.shootName}')
        kubectl --kubeconfig ./garden-kubeconfig.yaml annotate shoot $SHOOT_NAME confirmation.gardener.cloud/deletion=true
        kubectl --kubeconfig ./garden-kubeconfig.yaml delete shoot $SHOOT_NAME --force=true --wait=false

